### ISSUE TITLE
Create multiple question-types

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/capstone-project#13]
## Value Proposition
As a survey-creator I want to choose between different question types (e.g. 'yes/no', 'plain-text') to get different kinds of feedback from my subscribers

## Description
![Bildschirmfoto 2022-10-22 um 18 12 20](https://user-images.githubusercontent.com/111574974/197349720-9741f56d-8895-4cf4-afe7-3631beb75040.png)

## Acception Criteria
- [x] It is possible to choose a question type when creating a new survey
- [x] A preview is shown according to the chosen question type

## Tasks
- [x] create a select input field to choose an option
- [x] change the preview according to that option
- [x] if necessary apply more inputfields to get necessary data
