### ISSUE TITLE
feature create basic Layout and Styling

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/capstone-project#14]
## Value Proposition
As a user I want to have a continues styling on all pages to have a good user experience.

## Description
just a simple header including a logo

## Acception Criteria
- [x] There is a header on each site that displays the app-logo.

## Tasks
- [x] Create a Layout Component and append it to the _app.js
- [x] Create a headline h1 for the header
- [x] Create a Header component and append it to the Layout Component
