### ISSUE TITLE
feature: Implement Mongo DB

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/capstone-project#15]
## Value Proposition
As a survey creator I want to save the created/edited surveys permanently so I have access to it from everywhere at any time

## Description
first idears:

![Image](https://user-images.githubusercontent.com/111574974/197506684-be04a362-6115-448c-ad4f-45a3ddf9f2d3.png)

## Acception Criteria
- [x] The data the survey ceator add/edit is stored in a database
- [x] The list-view shows all actual surveys from the database

## Tasks
- [x] create a feature-branch for this issue
- [x] create a MongoDB and implement collections for the datastructure as shown above
- [x] install mongoose
- [x] create a database-connection to the database
- [x] set environment variables
- [x] create schema and model
- [x] use next-API to add, update and delete surveys
- [x] change service-functions getAllSurveys and getSurveyById to use next-API now

**Comment by PhilippWeiss85** [comment]
Hi Roland, good story but rather short for this kind of complex issue. Here are my improvement suggestions:
Would change your first AC to:
1. The data the survey ceator add/edit is stored in a database

Secondly I would suggest to add a bit more content to your tasks "develop a useful data structure for the app" is maybe to vage. If you don't know how your data structure looks like I would suggest you put the issue/user story on hold until you have a clear idea of how the data structure in your db should look like.

**Comment by Roland-Hufnagel** [comment]
I just use fake data at the moment and don't want to implement localStorage. You both are right. Thank you. I think about it and try to make the userstory a bit more detailed.
