### ISSUE TITLE
Basic Site with first functionality

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/capstone-project#2]
## Value Proposition
As a Subscriber , I want to see the survey with its title so that I can read the questions and give my personal answers and submit it.

## Description

![Bildschirmfoto 2022-10-14 um 15 39 12](https://user-images.githubusercontent.com/111574974/195861023-7e837edc-544d-4ddf-b308-993b8674b154.png)

## Acception Criteria
- [ ] The User can see the (dynamic) title to identify to be on the right website
- [ ] Interactivity: Form can be filled out and submitted
- [ ] A Success Message is shown to the user
- [ ] The questions in the form are created dynamically from example data

## Tasks
- [ ] create an array of questions as example data to be used in different forms
- [ ] make a dynamic-page with basic styling
- [ ] add a form with questions from faked data and input fields for the answers
- [ ] add a submit button
- [ ] implement function 'onSubmit' to get the form data and to show a "Thank You" Message

**Comment by ThomasF85** [comment]
The Value proposition should be a heading and the "<" and ">" should be deleted. The value proposition "I can input the first question and choose a question type from a list" i snot really a value for the end user. Putting a question into a list has no value in itself.

**Comment by Roland-Hufnagel** [comment]
I changed the issue completely and try it again. Please leave a comment.

**Comment by Roland-Hufnagel** [comment]
Thanx Philipp. I have updated the userstrory.
