### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/capstone-project#20]
## Value Proposition
As a user I that saves a new survey I want to see that something is happening in the background so I can be sure, the survey will be created. 

## Acception Criteria
- [ ] An animation is shown while the data is stored to the database. 

## Tasks
- [ ] create a new feature branch feature/progress-bar
- [ ] add a functionality to the onSubmit function that displays an animation.
- [ ] route to the list-view after saving the data

**Comment by PhilippWeiss85** [comment]
Hi Roland, LGMT
