### ISSUE TITLE
Third type of question

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/capstone-project#21]
## Value Proposition
As a survey creator I want a third type of question that I can choose from to make my surveys more divers.

## Description
![Bildschirmfoto 2022-11-01 um 20 02 47](https://user-images.githubusercontent.com/111574974/199316784-6460223f-9d78-4060-a81e-ea7dafeac023.png)

## Acception Criteria
- [ ] A third question-type can be chosen when creating new Questions
- [ ] A preview according to that question-type is shown
- [ ] The survey displays the new question-type

## Tasks
- [ ] create feature-branch feature/newQuestionType
- [ ] Modify the component CreateSurveyForm to choose the questiontype and display the preview
- [ ] Modify the component QuestionCard to display the new type
- [ ] Modify the component EvaluationCard to evaluate according to the new type

**Comment by PhilippWeiss85** [comment]
Hey Roland LGTM!
