### ISSUE TITLE
User Authentification

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/capstone-project#22]
## Value Proposition
As a survey creator I want nobody else to have access to my data so I am the owner of my surveys

## Description
![Bildschirmfoto 2022-11-02 um 11 54 23](https://user-images.githubusercontent.com/111574974/199472047-c55bb27c-7a91-4371-8d99-9c8a2d395f62.png)

## Acception Criteria
- [ ] CRUD Operations are only possible after logIn.
- [ ] Survey-List is filtered by user
- [ ] Survey-List is only displayed when user is logged in.

## Tasks
- [ ] create feature-branch feature/nextAuth
- [ ] install nextAuth
- [ ] setup nextAuth
- [ ] client side: Only render interactive components for CRUD-Operations when logged in
- [ ] server side: Only allow DB-Operations after User-Authentification
- [ ] SSR: Only render Surveys after User-Login
- [ ] Mongo-DB: Add a 'Owner-Property' to each survey
