### ISSUE TITLE
Graphical Evaluation

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/capstone-project#24]
## Value Proposition
As a survey creator I want to have a diagram in the evaluation to have a visual representation of the results

## Description
![Bildschirmfoto 2022-11-07 um 10 36 50](https://user-images.githubusercontent.com/111574974/200277073-3a961d86-89e3-43c4-b340-e249b46343a9.png)

## Acception Criteria
- [ ] The result of the yes/no questions is displayed in numbers and in a bar-diagram.

## Tasks
- [ ] create feature branch feature/graph
- [ ] istall rechart library
- [ ] change data-structure in evaluation to the supported format
- [ ] change component evaluationCard to display the chart

**Comment by Mark-Krensel** [comment]
Suggestion: Maybe you want to add a time/date stamp on the chart to see when you created the evaluation chart. That is because I guess you don't have a mechanism, which prevents users to give more answers at some point, so they might add more answers after you want to share your findings.

Otherwise a good story. I just don't know whether the back button is also part of the story or not.
