### ISSUE TITLE
Unit Testing and Component Testing

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/capstone-project#27]
## Value Proposition
As a developer I want to permanently test the app while developing

## Acception Criteria
- [x] There are unit-tests and component-tests in the project

## Tasks
- [x] create feature-branch feature/testing
- [x] implement testing functions
- [x] test the testing functions

**Comment by PhilippWeiss85** [comment]
Hi Roland,

I think you dont need to install testing libraries :) Jest is already installed in our projects.
