### ISSUE TITLE
Advanced Styling

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/capstone-project#28]
## Value Proposition
As a user I want to have a pretty design of the app so I have a good user experience.

## Acception Criteria
- [x] A pretty start page that asks for SignIn
- [x] A survey that looks good. 
- [x] A pretty "Thank You" page

## Tasks
- [x] create feature-branch feature/advancedStyling
- [x] design start-page, survey-page, thank-you-page

**Comment by F-Kirchhoff** [comment]
Hey Roland, you might think about explicit things you want to change about your styling to make the restyling process more structured.
