### ISSUE TITLE
See a list of all surveys

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/capstone-project#3]
## Value Proposition
As a survey-creator I want to see a list with all my surveys to have a good overview and be able to change to a detail-page to see specific information
Description

![Bildschirmfoto 2022-10-17 um 11 21 15](https://user-images.githubusercontent.com/111574974/196140505-122dcb35-1e19-4670-a148-8078ec7b37dc.png)

## Acception Criteria
- [ ] A list of all surveys is shown
- [ ] Each list item shows some information about the survey
- [ ] Each list item has a link to the specific detail page
- [ ] The detail page shows more specific information about this survey
- [ ] On the detail page is a link to go back to list-page

## Tasks
- [ ] Make example data: Use an array for basic data of all surveys and another array with specific data for each survey
- [ ] Create a component for the list with some basic styling
- [ ] Create a card-component for the list-item  with basic styling
- [ ] Create a card-component for detail-page with basic styling
- [ ] Implement the link to switch from list-view to detail-view
- [ ] Implement the link to go back from detail-view to list-view

**Comment by PhilippWeiss85** [comment]
Hi Roland!
I think the story is quite big and it could be good to split in two separate stories (1. Add list page with informations, 2. Add details page of list items).
Right now your AC and tasks are a bit vage and I think i would be good for your development process when you get a bit more precise (e.g. which exact data should be shown in the list page, how to you get the survey link displayed)

Except my comment above is like your story very much!

**Comment by F-Kirchhoff** [comment]
Hey Roland, very nice! Only one thing: what do you mean with 'shows some information'? It would be better to state explicitly what you mean. In your wire frame there is a copy button and display for the link to the survey. Do you mean that? And you need to add these components in your task list.

**Comment by Roland-Hufnagel** [comment]
I updated the wireframe and made some more detaild ACs

**Comment by Roland-Hufnagel** [comment]
I reduced the userstory a bit and updated the wireframe
