### ISSUE TITLE
Create a dynamic form

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/capstone-project#4]
## Value Proposition
As a survey creator I can add multiple questions to my survey so there is no limit for questions.

Description

![Bildschirmfoto 2022-10-17 um 17 11 16](https://user-images.githubusercontent.com/111574974/196215083-6ed4b39a-77ff-4e11-b596-66fbceb0038c.png)

## Acception Criteria

- [x] A form is shown to input a title of the survey
- [x] In the form there is an input field to type in the first question
- [x] A button is there that creates dynamically a new input field for the next question
- [x] There is no limit for adding new questions

## Tasks
- [x] Create a form-component with basic styling
- [x] Create an input field with basic styling 
- [x] Create a state-variable to hold the information
- [x] Create a "+" Button to dynamically generate one more input field

**Comment by F-Kirchhoff** [comment]
Hey Roland, die user story sieht soweit gut aus, du musst nur noch spezifizieren was man als Antwort typ auswählen kann. Falls du im Moment nur einen Typ hast, lass es weg und füge es bei einer kommenden user story hinzu.

**Comment by Roland-Hufnagel** [comment]
Danke, guter Hinweis. Ich habe die Userstory daran angepasst.
