### ISSUE TITLE
Add Delete and Save Button and functionality

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/capstone-project#5]
## Value Proposition
As a survey creator I want to be able to delete questions I have created before and save my just created survey.

## Description
![Bildschirmfoto 2022-10-17 um 20 41 30](https://user-images.githubusercontent.com/111574974/196256984-16db327f-eca3-4923-9a9d-407b0cc0a630.png)

## Acception Criteria
- [ ] To each question there is a Delete Button
- [ ] A Save Button will route to the list-view

## Tasks
- [ ] append the delete Button to every dynamically created Inputfield
- [ ] Implement delete-functionality: remove item from useState
- [ ] append a Submit Button to the form 
- [ ] implement the onSubmit function that routes to the list-view

**Comment by philmetscher** [comment]
Hey nice short user-story. If you use a `Button component` in Task 1 you could write:
"append `Button component` (delete) to every dynamically created input-field".
Another tip: You can nest the Task checkbox if you press 2x spacebar before a task. This would be useful for your tasks that are based on the button.
