### ISSUE TITLE
Add Delete Button to the List-View

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/capstone-project#6]
## Value Proposition
As a survey creator I want to be able to delete surveys from the list view, when I don't need them anymore.

## Description

![Bildschirmfoto 2022-10-17 um 20 53 45](https://user-images.githubusercontent.com/111574974/196260272-9ed35466-d2a2-4e22-832d-daac26b6b8d2.png)

## Acception Criteria
- [ ] There is a Delete Button to every list item that removes the item from the list.

## Tasks
- [ ] Add a Delete Button to the Card Component
- [ ] Implement functionality: update useState.

**Comment by philmetscher** [comment]
Same here 😃 If you use a `Button component` in Task 1 you could write:
"add `Button component` (delete) to the `Card component`"

optional feedback: I would write at AC:
"show a delete button foreach list-item, which removed those from the list and from the data-base (localStorage)"
