### ISSUE TITLE
Add Edit and Delete Button to the List View

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/capstone-project#7]
## Value Proposition
As a survey creator I want to be able to delete or edit existing surveys to change content, fix typos or add questions

## Description

![Bildschirmfoto 2022-10-17 um 21 28 50](https://user-images.githubusercontent.com/111574974/196265715-b5f50bc1-9347-41a6-9a4a-9b574e8d1015.png)

## Acception Criteria
- [x] In the list view there is an Edit-Button and a Delete-Button for each list item
- [x] Clicking the button will either delete the item or route to the create site to manipulate the data

## Tasks
- [x] append a Button Component (edit) to the card component
-- [ ] implement onClick: Delete the item
- [x] append a Button Component (delete) to the card component
-- [ ] implement onClick: Route to create-site
- [x] create-page shows the form with associated data ready to be changed

**Comment by sebsch1337** [comment]
Looks clean and tidy. I would suggest to seperate the last task to an own story (like the one for the edit form).

**Comment by F-Kirchhoff** [comment]
Hey Roland, its nice that you want to reuse your create page for the editing, it might get tricky though, but it is possible.

**Comment by Roland-Hufnagel** [comment]
Hi Felix, my solution feels a little bit unconventional but works fine. Can you give me a feedback for that solution?
