### ISSUE TITLE
Add a link to the list view that referres to this survey

### ISSUE THREAD

**Issue by Roland-Hufnagel** [Roland-Hufnagel/capstone-project#8]
## Value Proposition
As a survey creator I want to have a link to my survey, so I can copy the link and send it to my subscribers.

## Description

![Bildschirmfoto 2022-10-18 um 09 23 15](https://user-images.githubusercontent.com/111574974/196365087-e673ed24-4a1d-4800-beaf-662b208ac4ac.png)

## Acception Criteria
- [ ] In the list-view each list item has a link that referes to the survey

## Tasks
- [ ] create feature brach
- [ ] add a link to the example data
- [ ] add the link to the card component

**Comment by kai-franke** [comment]
Very useful feature, very clear user story.
